CREATE DATABASE IF NOT EXISTS devbook;

DROP TABLE IF EXISTS usuarios

CREATE TABLE usuarios (
    ID int UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Nick VARCHAR(50) NOT NULL unique,
    Email VARCHAR(50) NOT NULL unique,
    Senha VARCHAR(50) NOT NULL,
    CriadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);